---
- id: coding-standards
  name: Coding Standards
  description: Run consistency checks against coding standards
  entry: coding-standards.py
  language: python
  always_run: true
  pass_filenames: false
